/*
 * My stories API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.16
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The StoryPrivate model module.
 * @module model/StoryPrivate
 * @version v1
 */
export class StoryPrivate {
  /**
   * Constructs a new <code>StoryPrivate</code>.
   * @alias module:model/StoryPrivate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>StoryPrivate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StoryPrivate} obj Optional instance to populate.
   * @return {module:model/StoryPrivate} The populated <code>StoryPrivate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StoryPrivate();
      if (data.hasOwnProperty('body_markdown'))
        obj.bodyMarkdown = ApiClient.convertToType(data['body_markdown'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} bodyMarkdown
 */
StoryPrivate.prototype.bodyMarkdown = undefined;


