/*
 * My stories API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.16
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {Profile} from './Profile';

/**
 * The StoryImage model module.
 * @module model/StoryImage
 * @version v1
 */
export class StoryImage {
  /**
   * Constructs a new <code>StoryImage</code>.
   * @alias module:model/StoryImage
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>StoryImage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StoryImage} obj Optional instance to populate.
   * @return {module:model/StoryImage} The populated <code>StoryImage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StoryImage();
      if (data.hasOwnProperty('owner'))
        obj.owner = Profile.constructFromObject(data['owner']);
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('hadAudio'))
        obj.hadAudio = ApiClient.convertToType(data['hadAudio'], 'String');
      if (data.hasOwnProperty('favorited'))
        obj.favorited = ApiClient.convertToType(data['favorited'], 'String');
      if (data.hasOwnProperty('favoritesCount'))
        obj.favoritesCount = ApiClient.convertToType(data['favoritesCount'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'String');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/Profile} owner
 */
StoryImage.prototype.owner = undefined;

/**
 * @member {String} body
 */
StoryImage.prototype.body = undefined;

/**
 * Allowed values for the <code>language</code> property.
 * @enum {String}
 * @readonly
 */
StoryImage.LanguageEnum = {
  /**
   * value: "en"
   * @const
   */
  en: "en",

  /**
   * value: "es"
   * @const
   */
  es: "es",

  /**
   * value: "de"
   * @const
   */
  de: "de"
};

/**
 * @member {module:model/StoryImage.LanguageEnum} language
 */
StoryImage.prototype.language = undefined;

/**
 * @member {String} image
 */
StoryImage.prototype.image = undefined;

/**
 * @member {String} description
 */
StoryImage.prototype.description = undefined;

/**
 * @member {String} hadAudio
 */
StoryImage.prototype.hadAudio = undefined;

/**
 * @member {String} favorited
 */
StoryImage.prototype.favorited = undefined;

/**
 * @member {String} favoritesCount
 */
StoryImage.prototype.favoritesCount = undefined;

/**
 * @member {String} slug
 */
StoryImage.prototype.slug = undefined;

/**
 * @member {String} title
 */
StoryImage.prototype.title = undefined;

/**
 * @member {String} createdAt
 */
StoryImage.prototype.createdAt = undefined;

/**
 * @member {String} updatedAt
 */
StoryImage.prototype.updatedAt = undefined;


