/*
 * My stories API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.16
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {Profile} from './Profile';

/**
 * The Story model module.
 * @module model/Story
 * @version v1
 */
export class Story {
  /**
   * Constructs a new <code>Story</code>.
   * @alias module:model/Story
   * @class
   * @param bodyMarkdown {String} 
   * @param tags {Array.<String>} 
   * @param title {String} 
   */
  constructor(bodyMarkdown, tags, title) {
    this.bodyMarkdown = bodyMarkdown;
    this.tags = tags;
    this.title = title;
  }

  /**
   * Constructs a <code>Story</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Story} obj Optional instance to populate.
   * @return {module:model/Story} The populated <code>Story</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Story();
      if (data.hasOwnProperty('owner'))
        obj.owner = Profile.constructFromObject(data['owner']);
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('body_markdown'))
        obj.bodyMarkdown = ApiClient.convertToType(data['body_markdown'], 'String');
      if (data.hasOwnProperty('hadAudio'))
        obj.hadAudio = ApiClient.convertToType(data['hadAudio'], 'String');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('favorited'))
        obj.favorited = ApiClient.convertToType(data['favorited'], 'String');
      if (data.hasOwnProperty('favoritesCount'))
        obj.favoritesCount = ApiClient.convertToType(data['favoritesCount'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], ['String']);
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'String');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/Profile} owner
 */
Story.prototype.owner = undefined;

/**
 * @member {String} body
 */
Story.prototype.body = undefined;

/**
 * @member {String} bodyMarkdown
 */
Story.prototype.bodyMarkdown = undefined;

/**
 * @member {String} hadAudio
 */
Story.prototype.hadAudio = undefined;

/**
 * Allowed values for the <code>language</code> property.
 * @enum {String}
 * @readonly
 */
Story.LanguageEnum = {
  /**
   * value: "en"
   * @const
   */
  en: "en",

  /**
   * value: "es"
   * @const
   */
  es: "es",

  /**
   * value: "de"
   * @const
   */
  de: "de"
};

/**
 * @member {module:model/Story.LanguageEnum} language
 */
Story.prototype.language = undefined;

/**
 * @member {String} image
 */
Story.prototype.image = undefined;

/**
 * @member {String} description
 */
Story.prototype.description = undefined;

/**
 * @member {String} favorited
 */
Story.prototype.favorited = undefined;

/**
 * @member {String} favoritesCount
 */
Story.prototype.favoritesCount = undefined;

/**
 * @member {String} slug
 */
Story.prototype.slug = undefined;

/**
 * @member {Array.<String>} tags
 */
Story.prototype.tags = undefined;

/**
 * @member {String} title
 */
Story.prototype.title = undefined;

/**
 * @member {String} createdAt
 */
Story.prototype.createdAt = undefined;

/**
 * @member {String} updatedAt
 */
Story.prototype.updatedAt = undefined;


